name: 'Coverage Check'
description: 'Runs coverage check with specified parameters and generates a pull request with test results'

inputs:
  test-command:
    description: 'Command to run tests'
    required: true
  coverage-type:
    description: 'Type of coverage report'
    required: true
  desired-coverage:
    description: 'Desired coverage percentage'
    required: true
  max-iterations:
    description: 'Maximum number of iterations'
    required: true
  open-api-key:
    description: 'API key for the coverage tool'
    required: false
  github-token:
    description: 'GitHub token for authentication'
    required: true
  pr-github-token:
    description: 'GitHub token for creating PR and commenting'
    required: true
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.12'
  node-version:
    description: 'Node.js version to install'
    required: true
    default: '20.3.1'

outputs:
  previousCoverage:
    description: "Previous coverage"
  currentCoverage:
    description: "Current coverage"
runs:
  using: "node20"
  main: "index.js"
