name: 'Coverage Check'
description: 'Runs coverage check with specified parameters and generates a pull request with test results'

inputs:
  testCommand:
    description: 'Command to run tests'
    required: true
  coverageType:
    description: 'Type of coverage report'
    required: true
  desiredCoverage:
    description: 'Desired coverage percentage'
    required: true
  maxIterations:
    description: 'Maximum number of iterations'
    required: true
  openApiKey:
    description: 'API key for the coverage tool'
    required: false
  githubToken:
    description: 'GitHub token for authentication'
    required: true
  prGithubToken:
    description: 'GitHub token for creating PR and commenting'
    required: true
  runner:
    description: 'Runner for tests'
    required: true
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.12'
  node-version:
    description: 'Node.js version to install'
    required: true
    default: '20.3.1'

outputs:
  previousCoverage:
    description: "Previous coverage"
  currentCoverage:
    description: "Current coverage"
runs:
  using: "node20"
  main: "index.js"
